### PR TITLE
Add support for API key auth

### PR DESCRIPTION
**Pull request by nkrishnaswami**
Hi gsheets folks, any interest in supporting API keys?
If so, any changes you'd prefer to see in the PR?

### CODE REVIEW

**Comment by xflr6** [comment]
Thanks for the PR.

AFAIU https://developers.google.com/sheets/api/guides/authorizing, we usually need `credentials` (access user data) and might optionally provide `developerKey`, but one can also only provide `developerKey`. Do you have a use case for the latter case?

As for the API, let's snake_case the [`build()`](https://googleapis.github.io/google-api-python-client/docs/epy/googleapiclient.discovery-module.html#build) argument name `def __init__(self, credentials, developer_key=None)` and  raise an  error if both are `None`.  As I am not sure how useful supplying only `developerKey` is, so I am wondering if a separate constructor such as `.from_developler_key()` is needed.

**Comment by nkrishnaswami** [comment]
Hi!  The use case is for accessing public data as an identified app/project, but not as a particular logged in user:
```
When your application requests public data, the request doesn't need to be authorized, but does need to be accompanied by an identifier, such as an API key.
```

I'll update the PR to reflect your comments presently.

**Comment by nkrishnaswami** [comment]
Raising an error broke 85 tests -- many of them rely on being able to pass in no credentials --, so I held off on that

**Comment by xflr6** [comment]
Thanks for the changes, I think I can take it from here test-wise.

> The use case is for accessing public data as an identified app/project, but not as a particular logged in user

What I was wondering if you have any examples of public sheets that we could use for testing.

**Comment by nkrishnaswami** [comment]
Oh, duh! Sure, here's one I have been using:  Maine, US, posts a link to a new sheet daily at https://www.maine.gov/dhhs/mecdc/infectious-disease/epi/airborne/coronavirus/data.shtml
Today's is 
https://docs.google.com/spreadsheets/d/13Rbm5zKKLTFNyLZ2Z9YYHc5v6YpO_erMz1pZwiUtfiQ/edit#gid=0

**Comment by xflr6** [comment]
Great, thanks. Let me merge this and look at the tests.

**Comment by xflr6** [comment]
released [gsheets 0.5](https://pypi.org/project/gsheets/0.5/#files) (6e748640421310ecb87fea5d5dccb18170d0a58d)

**Pull request merged**
